spring:
  application:
    name: 03-security-jwt
  datasource:
    url: jdbc:postgresql://localhost:5434/tasks_security
    username: tasks_security
    password: tasks_security
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

app:
  jwt:
    secret: "${JWT_SECRET:local-dev-secret-please-change-in-production-0123456789abcdef}"
    expiration-millis: 3600000
